### ISSUE TITLE
Ike compatibility with windows

### ISSUE THREAD

**Issue by diniluca1789** [allenai/ike#225]
Hi,
congratulation for the applicaton and the approach. I tried to install Ike on windows 10 but I run into a problem, namely:

> ike@1.0.0 watch C:\dev\workspace\neos\tmp\ike\webapp
> gulp watch --color

ike 2016-08-12 09:40:21,614 INFO  o.a.i.EmbeddingBasedPhrasesSearcher - Loading phrase vectors ...
module.js:442
    throw err;
    ^

Error: Cannot find module 'C:\dev\workspace\neos\tmp\ike\webapp\node_modules\gulp\node_modules\v8flags\cache\5.0.71.57.flags.json'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\dev\workspace\neos\tmp\ike\webapp\node_modules\gulp\bin\gulp.js:25:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\PROGRA~1\\nodejs\\node.exe" "C:\\PROGRA~1\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! ike@1.0.0 watch: `gulp watch --color`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ike@1.0.0 watch script 'gulp watch --color'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ike package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp watch --color
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ike
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ike
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\workspace\neos\tmp\ike\webapp\npm-debug.log
ike [DEBUG] [08/12/2016 09:40:22.511] [ike-tool-akka.actor.default-dispatcher-4] [akka://ike-tool/user/IO-HTTP/listener-0] Binding to /0.0.0.0:8080
ike [DEBUG] [08/12/2016 09:40:22.582] [ike-tool-akka.actor.default-dispatcher-6] [akka://ike-tool/system/IO-TCP/selectors/$a/0] Successfully bound to /0:0:0:0:0:0:0:0:8080
ike [INFO] [08/12/2016 09:40:22.587] [ike-tool-akka.actor.default-dispatcher-4] [akka://ike-tool/user/IO-HTTP/listener-0] Bound to /0.0.0.0:8080
ike 2016-08-12 09:40:27,976 INFO  o.a.i.EmbeddingBasedPhrasesSearcher - Loading phrase vectors complete
ike 2016-08-12 09:40:27,977 INFO  o.a.i.EmbeddingBasedPhrasesSearcher - Loading phrase vectors ...
ike 2016-08-12 09:40:53,277 INFO  o.a.i.EmbeddingBasedPhrasesSearcher - Loading phrase vectors complete
ike [DEBUG] [08/12/2016 09:41:35.810] [ike-tool-akka.actor.default-dispatcher-3] [akka://ike-tool/system/IO-TCP/selectors/$a/0] New connection accepted
ike [DEBUG] [08/12/2016 09:41:35.814] [ike-tool-akka.actor.default-dispatcher-3] [akka://ike-tool/system/IO-TCP/selectors/$a/0] New connection accepted
ike [DEBUG] [08/12/2016 09:41:35.892] [ike-tool-akka.actor.default-dispatcher-5] [akka://ike-tool/user/IO-HTTP/listener-0/1] Dispatching GET request to http://localhost:8080/ to handler Actor[akka://ike-tool/system/IO-TCP/selectors/$a/1#935838599]
ike [DEBUG] [08/12/2016 09:41:38.570] [ike-tool-akka.actor.default-dispatcher-7] [akka://ike-tool/system/IO-TCP/selectors/$a/0] New connection accepted
ike [DEBUG] [08/12/2016 09:41:38.579] [ike-tool-akka.actor.default-dispatcher-4] [akka://ike-tool/user/IO-HTTP/listener-0/2] Dispatching GET request to http://localhost:8080/ to handler Actor[akka://ike-tool/system/IO-TCP/selectors/$a/3#2050110872]
ike [DEBUG] [08/12/2016 09:41:38.603] [ike-tool-akka.actor.default-dispatcher-3] [akka://ike-tool/user/IO-HTTP/listener-0/0] Connection was PeerClosed, awaiting TcpConnection termination...
ike [DEBUG] [08/12/2016 09:41:38.603] [ike-tool-akka.actor.default-dispatcher-9] [akka://ike-tool/user/IO-HTTP/listener-0/1] Connection was PeerClosed, awaiting TcpConnection termination...
ike [DEBUG] [08/12/2016 09:41:38.605] [ike-tool-akka.actor.default-dispatcher-9] [akka://ike-tool/user/IO-HTTP/listener-0/1] TcpConnection terminated, stopping
ike [DEBUG] [08/12/2016 09:41:38.605] [ike-tool-akka.actor.default-dispatcher-5] [akka://ike-tool/user/IO-HTTP/listener-0/0] TcpConnection terminated, stopping

The nlp-debug.log contains the following information:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\PROGRA~1\\nodejs\\node.exe',
1 verbose cli   'C:\\PROGRA~1\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle ike@1.0.0~prewatch: ike@1.0.0
6 silly lifecycle ike@1.0.0~prewatch: no script for prewatch, continuing
7 info lifecycle ike@1.0.0~watch: ike@1.0.0
8 verbose lifecycle ike@1.0.0~watch: unsafe-perm in lifecycle true
9 verbose lifecycle ike@1.0.0~watch: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\dev\workspace\neos\tmp\ike\webapp\node_modules\.bin;C:\PROGRA~1\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\HP\HP Performance Advisor;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\OpenVPN\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\PuTTY\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\wget-1.11.4-x64\;C:\Program Files (x86)\Skype\Phone\;C:\dev\Softs\unxutils\usr\local\wbin;C:\dev\workspace\neos\protoc-2.6.1-win32;C:\Program Files\CMake\bin;C:\Program Files (x86)\sbt\\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\luca.dini\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\luca.dini\AppData\Local\Programs\Python\Python36-32\;C:\Users\luca.dini\AppData\Roaming\npm
10 verbose lifecycle ike@1.0.0~watch: CWD: C:\dev\workspace\neos\tmp\ike\webapp
11 silly lifecycle ike@1.0.0~watch: Args: [ '/d /s /c', 'gulp watch --color' ]
12 silly lifecycle ike@1.0.0~watch: Returned: code: 1  signal: null
13 info lifecycle ike@1.0.0~watch: Failed to exec watch script
14 verbose stack Error: ike@1.0.0 watch: `gulp watch --color`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid ike@1.0.0
16 verbose cwd C:\dev\workspace\neos\tmp\ike\webapp
17 error Windows_NT 10.0.10586
18 error argv "C:\\PROGRA~1\\nodejs\\node.exe" "C:\\PROGRA~1\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error ike@1.0.0 watch: `gulp watch --color`
22 error Exit status 1
23 error Failed at the ike@1.0.0 watch script 'gulp watch --color'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ike package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp watch --color
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ike
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ike
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

My question is: is Ike supposed to work on windows or its compatibility is limited to linux systems?
Many thanks,
Luca
(ps of course I installed git and node.js)

**Comment by sbhaktha** [comment]
Hi Luca, We haven't looked into making IKE compatible with Windows. It has been intended to run only on Linux systems and that is what we have tested so far.

**Comment by diniluca1789** [comment]
Thanks for the answer, I'll let you know the results of the experiments. Just in case, do you have a prebuilt linux Virtualbox image.
Again, thanks for the answer,
Luca

**Comment by diniluca1789** [comment]
In case somebody is interested. Ike can run under windows 10, with the following modifications:
The first error is caused by the sbt-plugin trying to execute node.js, which invalidly look for "which npm" whereas on windows is "which npm.cmd". I guess the only solution is to modify the source code and recompile, as we did (probably some slightly less OS dependent solution is possible).
Second we had to change slashes in ike\webapp\gulpfile.js, namely replacing slashes and adding some assets directory:
   {
      js: 'app\\js\\DictApp.js',
      less: 'app\\css\\*.less',
      allLess: 'app\\css\\**\\*.less',
      build: '..\\public',
      jshint: 'app\\**\\*.js',
      assets: 'app\\assets\\**\\*'
    }

With this, ike seems to work plainly on a windows system.
Hope it might be useful to somebody,
Cheers,
Luca

**Comment by sbhaktha** [comment]
Great, thanks Luca! I will update the documentation with this info.
